#Create SQL Database
CREATE DATABASE IF NOT EXISTS airbnb_barcelona;

USE airbnb_barcelona;

SELECT *
FROM listings;

#What are ten neighborhoods with more listings? 
SELECT neighbourhood_group_cleansed, COUNT(id) AS count_sum
FROM listings
GROUP BY neighbourhood_group_cleansed
ORDER BY count_sum desc
LIMIT 10;


#What are ten neighborhoods with more superhosts? 
SELECT neighbourhood_group_cleansed, COUNT(host_is_superhost) AS superhosts
FROM listings
WHERE host_is_superhost = 't'
GROUP BY neighbourhood_group_cleansed
ORDER BY superhosts desc
LIMIT 10;


#What are the five neighborhoods more expensive?
SELECT neighbourhood_group_cleansed, ROUND(AVG(CAST(REPLACE(Price,'$','') AS UNSIGNED))) AS price_avg
FROM listings
GROUP BY neighbourhood_group_cleansed
ORDER BY price_avg desc
LIMIT 5;


# What are the most popular property types?
SELECT property_type, COUNT(property_type) AS num_of_props
FROM listings
GROUP BY property_type
ORDER BY num_of_props DESC;


# What is the monthly revenue generated by the highest-earning Airbnb hosts in Barcelona?
 SELECT id, listing_url, name, 30 - availability_30 AS booked_out_30 , 
CAST(REPLACE(Price,'$','') AS UNSIGNED) AS price_clean, 
CAST(REPLACE(Price,'$','') AS UNSIGNED)*(30 - availability_30) / beds AS proj_rev_30
FROM listings ORDER BY proj_rev_30 DESC LIMIT 20; 


# Which hosts have the highest number of listings
SELECT host_id, host_name, host_url, COUNT( DISTINCT id) as listings_per_host
FROM listings
GROUP BY host_id, host_name, host_url
ORDER BY listings_per_host DESC
LIMIT 15;